insert into public.playgrounds
  (name, description, location, is_fenced, has_shade, has_water, has_toilets, has_parking, surface_type, equipment)
values
  ('Tivoli Park Playground', 'Veliko igrišče v Tivoliju s senco dreves.',
    ST_SetSRID(ST_MakePoint(14.4936, 46.0569), 4326)::geography,
    true, true, true, true, true, 'tartan',
    '["swings","slides","climbing_wall","sandbox"]'),
  ('Park Zvezda', 'Majhno igrišče v centru mesta.',
    ST_SetSRID(ST_MakePoint(14.5060, 46.0495), 4326)::geography,
    false, true, false, false, false, 'sand',
    '["swings","slides"]'),
  ('Fužine Otroško Igrišče', 'Sodobno igrišče ob reki Ljubljanici.',
    ST_SetSRID(ST_MakePoint(14.5518, 46.0538), 4326)::geography,
    true, false, true, false, true, 'tartan',
    '["swings","slides","zipline","sandbox"]'),
  ('Trnovo Park', 'Zeleno igrišče ob cerkvi.',
    ST_SetSRID(ST_MakePoint(14.5014, 46.0430), 4326)::geography,
    true, true, false, false, false, 'grass',
    '["swings","climbing_wall"]'),
  ('Šiška Kids Zone', 'Veliko igrišče z veliko opreme.',
    ST_SetSRID(ST_MakePoint(14.4790, 46.0720), 4326)::geography,
    true, false, true, true, true, 'tartan',
    '["swings","slides","sandbox","climbing_wall","zipline"]'),
  ('Bežigrad Playground', 'Soseska v Bežigradu, primerno za majhne otroke.',
    ST_SetSRID(ST_MakePoint(14.5118, 46.0679), 4326)::geography,
    true, true, false, false, true, 'sand',
    '["swings","slides","sandbox"]'),
  ('Koseški Bajer', 'Ob jezeru s številnimi igrali in senco.',
    ST_SetSRID(ST_MakePoint(14.4690, 46.0645), 4326)::geography,
    false, true, true, true, true, 'gravel',
    '["swings","slides","climbing_wall"]'),
  ('Vič Playground', 'Skrito igrišče v mirnem delu Viča.',
    ST_SetSRID(ST_MakePoint(14.4820, 46.0370), 4326)::geography,
    true, true, false, false, false, 'grass',
    '["swings","slides"]'),
  ('Rudnik Family Park', 'Družinsko igrišče s parkom in toaletami.',
    ST_SetSRID(ST_MakePoint(14.5215, 46.0264), 4326)::geography,
    true, false, true, true, true, 'tartan',
    '["swings","slides","sandbox","zipline"]'),
  ('Moste Igrišče', 'Obnovljeno igrišče v Mostah.',
    ST_SetSRID(ST_MakePoint(14.5410, 46.0570), 4326)::geography,
    true, false, false, false, true, 'tartan',
    '["swings","slides","climbing_wall"]');
